Controller álbuns e músicas
SamuelSimoes31/Esspotify pull request #9
Opened 2022-09-09 21:49 UTC by ThallysRocha

# Controller álbuns e músicas
- Foram criadas as rotas, do álbum e músicas

2022-09-10 02:28 UTC, SamuelSimoes31 requested changes

2022-09-10 02:28 UTC, SamuelSimoes31 commented on back/src/controllers/albums.js
> +    const {name,image,year,createdAt,songs} = request.body;
O createdAt é gerado automaticamente, não tem que ser passado na requisição.

2022-09-10 02:28 UTC, SamuelSimoes31 commented on back/src/controllers/albums.js
>          if(await Album.findOne({ name })) return response.status(400).send({ error: 'Album already exists' });
Dois artistas diferentes não podem ter o mesmo nome de álbum?

2022-09-10 02:28 UTC, SamuelSimoes31 commented on back/src/controllers/albums.js
>          return response.status(400).send({ error: 'Register failed' });
Só essa mensagem de erro não tá sendo suficiente para dizer qual foi o erro. Aí ou adiciona mais retornos ao longo da função, ou imprime o error do catch.

2022-09-10 02:28 UTC, SamuelSimoes31 commented on back/src/controllers/songs.js
> +            if(!participations||(featuringArtist._id != request.userId)){
!==

2022-09-10 02:28 UTC, SamuelSimoes31 commented on back/src/controllers/albums.js
> +        await Promise.all(songs.map(async song =>{
Se songs não por passado o songs.map dá pau. Mas a o álbum aparetement é criado.

2022-09-10 02:28 UTC, SamuelSimoes31 commented on back/src/controllers/albums.js
> +            const albumSong = new Song({...song, album: album._id});
delete song.createdAt só para garantir que esse campo n é passado na criação. Tem q ser gerado automaticamente.

2022-09-10 02:28 UTC, SamuelSimoes31 commented on back/src/models/song.js
> +    require : true,
Aqui é require ou required?

2022-09-10 02:28 UTC, SamuelSimoes31 commented on back/src/controllers/songs.js
>  songsRouter.post('',async (request, response) => {
A rota tá meio que totalmente desaçociada do album e do artista. Tem que rever o momento em que cada rota vai acontecer.

2022-09-12 11:04 UTC, ThallysRocha commented on back/src/controllers/songs.js
> +            if(!participations||(featuringArtist._id != request.userId)){
!=

2022-09-12 11:05 UTC, ThallysRocha commented on back/src/controllers/songs.js
> +            if(!participations||(featuringArtist._id != request.userId)){
Um id é string, e o outro não.

2022-09-12 11:07 UTC, ThallysRocha commented on back/src/controllers/albums.js
>          if(await Album.findOne({ name })) return response.status(400).send({ error: 'Album already exists' });
Pensando bem, vc está certo. Só não poderia o mesmo artista ter dois álbuns com o mesmo nome.

2022-09-13 18:04 UTC, SamuelSimoes31 approved these changes

2022-09-13 18:04 UTC, merged